# Copyright [2024] [Kishoraditya]
#
# Licensed under the Creative Commons Attribution-NonCommercial 4.0 International License. 
# To view a copy of this license, visit https://creativecommons.org/licenses/by-nc/4.0/

# cybersec_sdk/config.yaml

sdk:
  name: "Cybersecurity SDK"
  version: "1.0.0"
  author: "OpenAI Assistant"
