version: '3.8'

services:
  app:
    build: .
    container_name: cyberguard_app
    ports:
      - "8501:8501"
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
